version: '3.1'
services:
  mongo:
    image: mongo:4
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
    - ./storage/rabbitmq:/var/lib/rabbitmq
    ports:
    - 5672:5672
    - 15672:15672

  redis:
    image: 4-alpine
    volumes:
    - ./storage/redis:/data
    ports:
    - 6379:6379